import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {empty,session,ordered,filtered,see,answer,override,totals,canReveal,validateImport,reconcileFlags,normalizeSettings,sessionSize} from '../engine.js';
const bank=JSON.parse(fs.readFileSync(new URL('../data/question-bank.json',import.meta.url))).questions;
test('all questions have source lineage, four options, rationales and neutral assets',()=>{assert.equal(bank.length,95);for(const q of bank){assert.equal(new Set(q.options).size,4);assert.equal(q.choice_rationales.length,4);assert.equal(new Set(q.choice_rationales).size,4);assert(q.choice_rationales.every(x=>x.length>25));for(const k of ['image','zoom_image','original_image']){assert.match(q[k],/^assets\/[a-f0-9]{24}\.(webp|png)$/);assert(fs.existsSync(new URL('../'+q[k],import.meta.url)));}assert(q.visual_target);assert(q.citations.length>=2);assert(q.asset_id&&q.variant_id&&q.source_group_id);}});
test('source groups rotate before repeating when alternatives remain',()=>{for(let k=0;k<100;k++){let a=ordered(bank);assert.equal(new Set(a.map(q=>q.question_id)).size,bank.length);const first=new Set(a.slice(0,Math.min(10,new Set(bank.map(q=>q.source_group_id)).size)).map(q=>q.source_group_id));assert.equal(first.size,Math.min(10,new Set(bank.map(q=>q.source_group_id)).size));for(let i=1;i<a.length;i++){if(a[i].source_group_id===a[i-1].source_group_id)assert(a.slice(i).every(q=>q.source_group_id===a[i].source_group_id));}}});
test('choice/rationale alignment survives order randomization',()=>{for(let k=0;k<100;k++){const s=session(bank);for(const i of s.items){const q=bank.find(q=>q.question_id===i.id);assert.deepEqual([...i.order].sort(),[0,1,2,3]);i.order.forEach(x=>assert(q.options[x]&&q.choice_rationales[x]));}}});
test('drafts, skipped items, locked answers, counts and corrections',()=>{const p=empty(),s=session(bank,'learn');p.session=s;const it=s.items[0],q=bank.find(q=>q.question_id===it.id);see(p,q,it);see(p,q,it);assert.equal(p.questions[q.question_id].times_seen,1);assert.equal(canReveal(s,it),false);it.draft=(q.correct_index+1)%4;s.index=1;s.index=0;assert.notEqual(it.draft,null);answer(p,q,it);assert.equal(canReveal(s,it),true);assert.equal(answer(p,q,it),false);assert.equal(filtered(bank,p,{filter:'incorrect'}).length,1);assert.equal(override(p,q,it),true);assert.equal(override(p,q,it),false);assert.equal(p.questions[q.question_id].times_answered,1);assert.equal(p.questions[q.question_id].incorrect_count,0);assert.equal(filtered(bank,p,{filter:'incorrect'}).length,0);assert.equal(totals(s).unanswered,bank.length-1);assert.equal(totals(s).correct,1);assert.deepEqual(validateImport(JSON.parse(JSON.stringify(p)),bank),p);});
test('exam feedback is deferred even for locked answers',()=>{const p=empty(),s=session(bank,'exam');const it=s.items[0],q=bank.find(q=>q.question_id===it.id);it.draft=q.correct_index;answer(p,q,it);assert.equal(canReveal(s,it),false);s.complete=true;assert.equal(canReveal(s,it),true);});
test('source-aware unseen filtering and category counts',()=>{const p=empty(),s=session(bank),it=s.items.find(i=>bank.find(q=>q.question_id===i.id).category==='Diagram'),q=bank.find(q=>q.question_id===it.id);see(p,q,it);const same=bank.filter(x=>x.source_group_id===q.source_group_id);assert.equal(filtered(bank,p,{filter:'unseen'}).length,bank.length-same.length);assert.equal(filtered(bank,p,{category:'Diagram',filter:'unseen'}).length,bank.filter(x=>x.category==='Diagram').length-same.filter(x=>x.category==='Diagram').length);});
test('length caps at available items and bad imports fail closed',()=>{assert.equal(session(bank,'learn','40').items.length,40);assert.throws(()=>validateImport({schema_version:55},bank));const p=empty();p.questions.bad={};assert.throws(()=>validateImport(p,bank));});
test('all scored sources usable and variants linked, non-scored sources excluded',()=>{const m=JSON.parse(fs.readFileSync(new URL('../data/source-manifest.json',import.meta.url)));for(const q of bank){const s=m.sources.find(s=>s.source_id===q.source_id);assert.equal(s.status,'USABLE');assert((s.variants||[{variant_id:s.variant_id}]).some(v=>v.variant_id===q.variant_id));}assert.equal(m.sources.length,62);assert.equal(m.sources.filter(s=>s.status!=='USABLE').length,19);});
test('multi-lecture selection supports all, individual, mixed and none',()=>{const p=empty();assert.equal(filtered(bank,p,{collection:[]}).length,0);assert.equal(filtered(bank,p,{collection:['R1']}).length,19);assert.equal(filtered(bank,p,{collection:['R2']}).length,6);assert.equal(filtered(bank,p,{collection:['R4']}).length,16);assert.equal(filtered(bank,p,{collection:['R5']}).length,11);assert.equal(filtered(bank,p,{collection:['R6']}).length,15);assert.equal(filtered(bank,p,{collection:['R7']}).length,11);assert.equal(filtered(bank,p,{collection:['R1','R2']}).length,25);assert.equal(filtered(bank,p,{collection:['R8']}).length,13);assert.equal(filtered(bank,p,{collection:['R9']}).length,4);assert.equal(filtered(bank,p,{collection:'all'}).length,95);});
test('stored preferences are bounded, migrate prior lecture value and handle changed banks',()=>{let s=normalizeSettings({mode:'exam',length:'40',category:'TEM',collection:['R1'],filter:'marked'},bank);assert.deepEqual(s,{mode:'exam',length:'40',category:'TEM',collection:['R1'],filter:'marked'});assert.deepEqual(normalizeSettings({collection:'R1'},bank).collection,['R1']);assert.equal(normalizeSettings({collection:['missing']},bank).collection,'all');assert.deepEqual(normalizeSettings({collection:[]},bank).collection,[]);assert.equal(normalizeSettings({mode:'bad',length:'-4',category:'bad',filter:'bad'},bank).mode,'learn');});
test('displayed actual count equals built session size',()=>{for(const length of ['10','20','40','all','endless']){assert.equal(sessionSize(bank.length,length),session(bank,'learn',length).items.length);assert.equal(sessionSize(0,length),0);}assert.equal(sessionSize(3,'40'),3);});

test('learner flag remediation resolves only pre-batch flags once and preserves deliberate reopen',()=>{const p=empty();const id=bank[0].question_id;const batch={batch_id:'batch-a',created_at:'2026-10-06T11:00:00-04:00',flagged_question_ids:[id]};p.flags[id]={status:'open',date:'2026-10-06T14:00:00Z',note:'mask leak'};assert.equal(reconcileFlags(p,batch),1);assert.equal(p.flags[id].status,'resolved');p.flags[id].status='open';p.flags[id].date='2026-10-06T16:00:00Z';assert.equal(reconcileFlags(p,batch),0);assert.equal(p.flags[id].status,'open');const later=empty();later.flags[id]={status:'open',date:'2026-10-06T16:00:00Z'};assert.equal(reconcileFlags(later,batch),0);assert.equal(later.flags[id].status,'open');});
